/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.SelecaoMaquinas.SelecaoMaquinas;
import controller.MaquinaDAO;
import model.Pesquisa;
import controller.PesquisaDAO;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import z_ux.JTableUtilities;
import view.framesCadastro.FrameCadastroColaborador;
import view.framesCadastro.FrameCadastroGrupo;
import view.framesCadastro.FrameCadastroMaquinas;
import view.framesRelatorio.FrameRelatorioColaborador;
import view.framesRelatorio.FrameRelatorioGeral;
import view.menu.Sobre;

/**
 *
 * @author Thulio
 */
public class TelaApp extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    FrameCadastroMaquinas cadMaq;
    FrameCadastroGrupo cadGru;
    FrameCadastroColaborador cadColab;
    FrameRelatorioColaborador relColab;
    FrameRelatorioGeral relGeral;
    public static SelecaoMaquinas telaSelecaoMaq;

    /**
     * Creates new form TelaApp
     */
    public TelaApp() {
        initComponents();

        lerBanco();

        //Criação dos Paineis do Cadastro
        cadMaq = new FrameCadastroMaquinas();
        cadGru = new FrameCadastroGrupo();
        cadColab = new FrameCadastroColaborador();

        jPainelDinamicoCad.setLayout(layout);

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        c.ipady = 10;

        jPainelDinamicoCad.add(cadMaq, c);
        jPainelDinamicoCad.add(cadGru, c);
        jPainelDinamicoCad.add(cadColab, c);

        cadMaq.setVisible(false);
        cadGru.setVisible(false);
        cadColab.setVisible(false);

        //Criação dos Paineis do Relatório
        relColab = new FrameRelatorioColaborador();
        relGeral = new FrameRelatorioGeral();

        jPainelDinamicoRel.setLayout(layout);

        c.ipady = 0;
        c.ipadx = 0;

        jPainelDinamicoRel.add(relColab, c);
        jPainelDinamicoRel.add(relGeral, c);

        relColab.setVisible(false);
        relGeral.setVisible(false);

    }

    public void lerBanco() {
        DefaultTableModel modelo = (DefaultTableModel) jTableBD.getModel();
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.LEFT, 0);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 1);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 2);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 3);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 4);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 5);
        JTableUtilities.alinharColuna(jTableBD, SwingConstants.CENTER, 7);
        JTableUtilities.centralizarHeader(jTableBD);

        PesquisaDAO p = new PesquisaDAO();
        modelo.setNumRows(0);

        for (Pesquisa i : p.listar()) {

            modelo.addRow(new Object[]{
                i.getId(),
                i.getPesquisa(),
                i.getData(),
                i.getPergunta(),
                i.getResposta(),
                i.getId_colaborador(),
                i.getGrupo(),
                i.getMaquina()
            });

        }

    }

    public void classificarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableBD.getModel();
        jTableBD.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);
        lerBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCadastro = new javax.swing.JTable();
        jTabs = new javax.swing.JTabbedPane();
        jPanelBD = new javax.swing.JPanel();
        jPanelBtnBD = new javax.swing.JPanel();
        jBtnBDApagar = new javax.swing.JButton();
        jBtnBDLer = new javax.swing.JButton();
        logoFSFX = new javax.swing.JLabel();
        logoHMC = new javax.swing.JLabel();
        jPanelTabelaBD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBD = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelRelatorio = new javax.swing.JPanel();
        jPanelBtnRel = new javax.swing.JPanel();
        jBtnRelGeral = new javax.swing.JButton();
        jBtnRelGrupo = new javax.swing.JButton();
        logoHMC1 = new javax.swing.JLabel();
        logoFSFX1 = new javax.swing.JLabel();
        jPainelDinamicoRel = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jPanelBtnCad = new javax.swing.JPanel();
        jBtnCadColaborador = new javax.swing.JButton();
        jBtnCadMaq = new javax.swing.JButton();
        jBtnCadGrupo = new javax.swing.JButton();
        logoHMC2 = new javax.swing.JLabel();
        logoFSFX2 = new javax.swing.JLabel();
        jPainelDinamicoCad = new javax.swing.JPanel();
        jMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConfigBD = new javax.swing.JMenuItem();
        jMenuItemConfigUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSobreSobre = new javax.swing.JMenuItem();

        jTableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCadastro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::   SISTEMA DE CONTROLE DE SATISFAÇÃO - CORMED / WINNER   ::");
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTabs.setBackground(new java.awt.Color(204, 204, 255));
        jTabs.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTabs.setPreferredSize(new java.awt.Dimension(950, 636));

        jPanelBD.setBackground(new java.awt.Color(102, 102, 102));

        jPanelBtnBD.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBtnBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBtnBD.setPreferredSize(new java.awt.Dimension(942, 91));

        jBtnBDApagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnBDApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/deletar_bd.png"))); // NOI18N
        jBtnBDApagar.setText("APAGAR");
        jBtnBDApagar.setToolTipText("Apagar registros importados");
        jBtnBDApagar.setMaximumSize(new java.awt.Dimension(67, 23));
        jBtnBDApagar.setMinimumSize(new java.awt.Dimension(67, 23));
        jBtnBDApagar.setPreferredSize(new java.awt.Dimension(67, 23));
        jBtnBDApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBDApagarActionPerformed(evt);
            }
        });
        jBtnBDApagar.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnBDApagar.setHorizontalTextPosition(SwingConstants.CENTER);

        jBtnBDLer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnBDLer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/ler.png"))); // NOI18N
        jBtnBDLer.setText("LER");
        jBtnBDLer.setToolTipText("Ler máquinas cadastradas");
        jBtnBDLer.setMaximumSize(new java.awt.Dimension(67, 23));
        jBtnBDLer.setMinimumSize(new java.awt.Dimension(67, 23));
        jBtnBDLer.setPreferredSize(new java.awt.Dimension(67, 23));
        jBtnBDLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBDLerActionPerformed(evt);
            }
        });
        jBtnBDLer.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnBDLer.setHorizontalTextPosition(SwingConstants.CENTER);

        logoFSFX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/fsfx.png"))); // NOI18N

        logoHMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/logo-hmc.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBtnBDLayout = new javax.swing.GroupLayout(jPanelBtnBD);
        jPanelBtnBD.setLayout(jPanelBtnBDLayout);
        jPanelBtnBDLayout.setHorizontalGroup(
            jPanelBtnBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnBDLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBtnBDLer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnBDApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBtnBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoHMC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoFSFX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBtnBDLayout.setVerticalGroup(
            jPanelBtnBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnBDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtnBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBtnBDLayout.createSequentialGroup()
                        .addComponent(logoFSFX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoHMC))
                    .addGroup(jPanelBtnBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnBDApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnBDLer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTabelaBD.setBackground(new java.awt.Color(102, 102, 102));

        jTableBD.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PESQUISA", "DATA", "PERGUNTA", "RESPOSTA", "COLABORADOR", "GRUPO", "MAQUINA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBD.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableBD);
        jTableBD.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableBD.getColumnModel().getColumnCount() > 0) {
            jTableBD.getColumnModel().getColumn(0).setMinWidth(60);
            jTableBD.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableBD.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableBD.getColumnModel().getColumn(1).setMinWidth(100);
            jTableBD.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableBD.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableBD.getColumnModel().getColumn(2).setMinWidth(100);
            jTableBD.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableBD.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableBD.getColumnModel().getColumn(3).setMinWidth(80);
            jTableBD.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableBD.getColumnModel().getColumn(3).setMaxWidth(80);
            jTableBD.getColumnModel().getColumn(4).setMinWidth(80);
            jTableBD.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableBD.getColumnModel().getColumn(4).setMaxWidth(80);
            jTableBD.getColumnModel().getColumn(5).setMinWidth(110);
            jTableBD.getColumnModel().getColumn(5).setPreferredWidth(110);
            jTableBD.getColumnModel().getColumn(5).setMaxWidth(110);
            jTableBD.getColumnModel().getColumn(7).setMinWidth(225);
            jTableBD.getColumnModel().getColumn(7).setPreferredWidth(225);
            jTableBD.getColumnModel().getColumn(7).setMaxWidth(225);
        }

        javax.swing.GroupLayout jPanelTabelaBDLayout = new javax.swing.GroupLayout(jPanelTabelaBD);
        jPanelTabelaBD.setLayout(jPanelTabelaBDLayout);
        jPanelTabelaBDLayout.setHorizontalGroup(
            jPanelTabelaBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabelaBDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTabelaBDLayout.setVerticalGroup(
            jPanelTabelaBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaBDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jCheckBox1.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ADICIONAR CLASSIFICADORES");
        jCheckBox1.setToolTipText("Adiciona classificadores na tabela");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBDLayout = new javax.swing.GroupLayout(jPanelBD);
        jPanelBD.setLayout(jPanelBDLayout);
        jPanelBDLayout.setHorizontalGroup(
            jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBtnBD, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
            .addComponent(jPanelTabelaBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBDLayout.setVerticalGroup(
            jPanelBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBDLayout.createSequentialGroup()
                .addComponent(jPanelBtnBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTabelaBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("/_imagens/bd.png"));
        } catch (IOException e) {
        }
        jTabs.addTab("BANCO DE DADOS", jPanelBD);
        setIconImage(img);

        jPanelRelatorio.setBackground(new java.awt.Color(102, 102, 102));

        jPanelBtnRel.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBtnRel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBtnRel.setPreferredSize(new java.awt.Dimension(942, 91));

        jBtnRelGeral.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnRelGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/geral.png"))); // NOI18N
        jBtnRelGeral.setText("GERAL");
        jBtnRelGeral.setToolTipText("Gerar relatório Geral por Grupo");
        jBtnRelGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelGeralActionPerformed(evt);
            }
        });
        jBtnRelGeral.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnRelGeral.setHorizontalTextPosition(SwingConstants.CENTER);

        jBtnRelGrupo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnRelGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/user.png"))); // NOI18N
        jBtnRelGrupo.setText("COLABORADOR");
        jBtnRelGrupo.setToolTipText("Gerar relatório de Colaborador por Grupo");
        jBtnRelGrupo.setBorder(null);
        jBtnRelGrupo.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jBtnRelGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelGrupoActionPerformed(evt);
            }
        });
        jBtnRelGrupo.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnRelGrupo.setHorizontalTextPosition(SwingConstants.CENTER);

        logoHMC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/logo-hmc.png"))); // NOI18N

        logoFSFX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/fsfx.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBtnRelLayout = new javax.swing.GroupLayout(jPanelBtnRel);
        jPanelBtnRel.setLayout(jPanelBtnRelLayout);
        jPanelBtnRelLayout.setHorizontalGroup(
            jPanelBtnRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnRelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBtnRelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addGroup(jPanelBtnRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoHMC1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoFSFX1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBtnRelLayout.setVerticalGroup(
            jPanelBtnRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnRelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtnRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBtnRelLayout.createSequentialGroup()
                        .addComponent(logoFSFX1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoHMC1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBtnRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnRelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnRelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPainelDinamicoRel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPainelDinamicoRelLayout = new javax.swing.GroupLayout(jPainelDinamicoRel);
        jPainelDinamicoRel.setLayout(jPainelDinamicoRelLayout);
        jPainelDinamicoRelLayout.setHorizontalGroup(
            jPainelDinamicoRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPainelDinamicoRelLayout.setVerticalGroup(
            jPainelDinamicoRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRelatorioLayout = new javax.swing.GroupLayout(jPanelRelatorio);
        jPanelRelatorio.setLayout(jPanelRelatorioLayout);
        jPanelRelatorioLayout.setHorizontalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBtnRel, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
            .addComponent(jPainelDinamicoRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRelatorioLayout.setVerticalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioLayout.createSequentialGroup()
                .addComponent(jPanelBtnRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPainelDinamicoRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        jTabs.addTab("RELATÓRIOS", jPanelRelatorio);

        jPanelBtnCad.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBtnCad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBtnCad.setPreferredSize(new java.awt.Dimension(950, 91));

        jBtnCadColaborador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnCadColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/user.png"))); // NOI18N
        jBtnCadColaborador.setText("COLABORADOR");
        jBtnCadColaborador.setToolTipText("Cadastrar Colaborador");
        jBtnCadColaborador.setBorder(null);
        jBtnCadColaborador.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jBtnCadColaborador.setMaximumSize(new java.awt.Dimension(67, 23));
        jBtnCadColaborador.setMinimumSize(new java.awt.Dimension(67, 23));
        jBtnCadColaborador.setPreferredSize(new java.awt.Dimension(67, 23));
        jBtnCadColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadColaboradorActionPerformed(evt);
            }
        });
        jBtnCadColaborador.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnCadColaborador.setHorizontalTextPosition(SwingConstants.CENTER);

        jBtnCadMaq.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnCadMaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/pc.png"))); // NOI18N
        jBtnCadMaq.setText("MÁQUINA");
        jBtnCadMaq.setToolTipText("Cadastrar Máquina");
        jBtnCadMaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadMaqActionPerformed(evt);
            }
        });
        jBtnCadMaq.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnCadMaq.setHorizontalTextPosition(SwingConstants.CENTER);

        jBtnCadGrupo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnCadGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/geral.png"))); // NOI18N
        jBtnCadGrupo.setText("GRUPO");
        jBtnCadGrupo.setToolTipText("Cadastrar Grupo");
        jBtnCadGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadGrupoActionPerformed(evt);
            }
        });
        jBtnCadGrupo.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnCadGrupo.setHorizontalTextPosition(SwingConstants.CENTER);

        logoHMC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/logo-hmc.png"))); // NOI18N

        logoFSFX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/fsfx.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBtnCadLayout = new javax.swing.GroupLayout(jPanelBtnCad);
        jPanelBtnCad.setLayout(jPanelBtnCadLayout);
        jPanelBtnCadLayout.setHorizontalGroup(
            jPanelBtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnCadLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBtnCadColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCadGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCadMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoHMC2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoFSFX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBtnCadLayout.setVerticalGroup(
            jPanelBtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBtnCadLayout.createSequentialGroup()
                        .addComponent(logoFSFX2)
                        .addGap(12, 12, 12)
                        .addComponent(logoHMC2))
                    .addGroup(jPanelBtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnCadColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCadGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCadMaq, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPainelDinamicoCad.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPainelDinamicoCadLayout = new javax.swing.GroupLayout(jPainelDinamicoCad);
        jPainelDinamicoCad.setLayout(jPainelDinamicoCadLayout);
        jPainelDinamicoCadLayout.setHorizontalGroup(
            jPainelDinamicoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        jPainelDinamicoCadLayout.setVerticalGroup(
            jPainelDinamicoCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelDinamicoCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBtnCad, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addComponent(jPanelBtnCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPainelDinamicoCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabs.addTab("CADASTRO", jPanelCadastro);

        ImageIcon iconBd = new ImageIcon( getClass().getResource("/_imagens/bd.png") );
        jTabs.setIconAt(0, iconBd);

        ImageIcon iconRel = new ImageIcon( getClass().getResource("/_imagens/relatorio.png") );
        jTabs.setIconAt(1, iconRel);

        ImageIcon iconCad = new ImageIcon( getClass().getResource("/_imagens/cadastro.png") );
        jTabs.setIconAt(2, iconCad);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 349;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(jTabs, gridBagConstraints);

        jMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenu1.setText("CONFIGURAR");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItemConfigBD.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jMenuItemConfigBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/database.png"))); // NOI18N
        jMenuItemConfigBD.setText("Banco de Dados");
        jMenuItemConfigBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigBDActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConfigBD);

        jMenuItemConfigUsuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jMenuItemConfigUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/user-icon.png"))); // NOI18N
        jMenuItemConfigUsuarios.setText("Usuários");
        jMenu1.add(jMenuItemConfigUsuarios);

        jMenu.add(jMenu1);

        jMenu2.setText("SOBRE");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItemSobreSobre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jMenuItemSobreSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/info.png"))); // NOI18N
        jMenuItemSobreSobre.setText("Sobre o Software");
        jMenuItemSobreSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreSobreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSobreSobre);

        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        getAccessibleContext().setAccessibleName(":: CORMED SISAT 2.0 ::");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBDApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBDApagarActionPerformed
        String message = "DESEJA REALMENTE APAGAR O BANCO DE DADOS ? ";
        String title = "CONFIRME OPERAÇÃO";
        // display the JOptionPane showConfirmDialog
        int resposta = JOptionPane.showConfirmDialog(jPanelBD, message, title, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            jCheckBox1.setEnabled(true);
            jCheckBox1.setSelected(false);
            jTableBD.setRowSorter(null);
            PesquisaDAO dao = new PesquisaDAO();
            dao.truncarBD();
            MaquinaDAO m = new MaquinaDAO();
            m.resetarImportados();
        }
        lerBanco();
    }//GEN-LAST:event_jBtnBDApagarActionPerformed

    private void jBtnCadGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadGrupoActionPerformed
        cadColab.setVisible(false);
        cadMaq.setVisible(false);
        cadGru.setVisible(true);
        FrameCadastroGrupo g = new FrameCadastroGrupo();
        g.lerGrupos();
    }//GEN-LAST:event_jBtnCadGrupoActionPerformed

    private void jBtnCadMaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadMaqActionPerformed
        cadColab.setVisible(false);
        cadGru.setVisible(false);
        cadMaq.setVisible(true);
        FrameCadastroMaquinas m = new FrameCadastroMaquinas();
        m.lerMaquinas();
    }//GEN-LAST:event_jBtnCadMaqActionPerformed

    private void jBtnCadColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadColaboradorActionPerformed
        cadGru.setVisible(false);
        cadMaq.setVisible(false);
        cadColab.setVisible(true);
        FrameCadastroColaborador f = new FrameCadastroColaborador();
        f.lerColaboradores();
    }//GEN-LAST:event_jBtnCadColaboradorActionPerformed

    private void jBtnRelGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelGeralActionPerformed
        relColab.setVisible(false);
        relGeral.setVisible(true);
    }//GEN-LAST:event_jBtnRelGeralActionPerformed

    private void jBtnRelGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelGrupoActionPerformed
        relGeral.setVisible(false);
        relColab.setVisible(true);
    }//GEN-LAST:event_jBtnRelGrupoActionPerformed

    private void jBtnBDLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBDLerActionPerformed
        telaSelecaoMaq = new SelecaoMaquinas(this, true);
        telaSelecaoMaq.setVisible(true);
    }//GEN-LAST:event_jBtnBDLerActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        classificarTabela();
        jCheckBox1.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenuItemSobreSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreSobreActionPerformed
        Sobre s = new Sobre();
        //this.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreSobreActionPerformed

    private void jMenuItemConfigBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConfigBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBDApagar;
    private javax.swing.JButton jBtnBDLer;
    private javax.swing.JButton jBtnCadColaborador;
    private javax.swing.JButton jBtnCadGrupo;
    private javax.swing.JButton jBtnCadMaq;
    private javax.swing.JButton jBtnRelGeral;
    private javax.swing.JButton jBtnRelGrupo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItemConfigBD;
    private javax.swing.JMenuItem jMenuItemConfigUsuarios;
    private javax.swing.JMenuItem jMenuItemSobreSobre;
    private javax.swing.JPanel jPainelDinamicoCad;
    private javax.swing.JPanel jPainelDinamicoRel;
    private javax.swing.JPanel jPanelBD;
    private javax.swing.JPanel jPanelBtnBD;
    private javax.swing.JPanel jPanelBtnCad;
    private javax.swing.JPanel jPanelBtnRel;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelRelatorio;
    private javax.swing.JPanel jPanelTabelaBD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBD;
    private javax.swing.JTable jTableCadastro;
    private javax.swing.JTabbedPane jTabs;
    private javax.swing.JLabel logoFSFX;
    private javax.swing.JLabel logoFSFX1;
    private javax.swing.JLabel logoFSFX2;
    private javax.swing.JLabel logoHMC;
    private javax.swing.JLabel logoHMC1;
    private javax.swing.JLabel logoHMC2;
    // End of variables declaration//GEN-END:variables
}
