/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.framesCadastro;

import controller.PerguntaDAO;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import model.Pergunta;
import z_ux.JTableUtilities;

/**
 *
 * @author Thulio
 */
public class FrameCadastroPergunta extends javax.swing.JPanel {

    //Variavel para controlar se o botao ADD fara uma inclusão ou alteração
    static int op;

    /**
     * Creates new form FrameCadastroGrupo
     */
    public FrameCadastroPergunta() {
        initComponents();
        lerPerguntas();

        
        //Esconder os Campos ao Iniciar Frame
        esconderCampos();
    }

    public void lerPerguntas() {
        DefaultTableModel modelo = (DefaultTableModel) jTablePerguntas.getModel();
        JTableUtilities.centralizarHeader(jTablePerguntas);
        JTableUtilities.alinharColuna(jTablePerguntas, SwingConstants.CENTER, 0);
        PerguntaDAO p = new PerguntaDAO();
        modelo.setNumRows(0);

        for (Pergunta i : p.listar()) {

            modelo.addRow(new Object[]{
                i.getId(),
                i.getPergunta()
            });
        }
    }

    public void esconderCampos() {
        jLabel2.setVisible(false);
        jTxtPergunta.setVisible(false);
        jPanel2.setVisible(false);
    }

    public void mostrarCampos() {
        jLabel2.setVisible(true);
        jTxtPergunta.setVisible(true);
        jPanel2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotoes = new javax.swing.JPanel();
        jBtnPergUPD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePerguntas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtPergunta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnADD = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(698, 369));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBotoes.setBackground(new java.awt.Color(153, 153, 153));

        jBtnPergUPD.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPergUPD.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jBtnPergUPD.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPergUPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/edit.png"))); // NOI18N
        jBtnPergUPD.setToolTipText("Editar Pergunta");
        jBtnPergUPD.setBorder(null);
        jBtnPergUPD.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jBtnPergUPD.setMaximumSize(new java.awt.Dimension(60, 60));
        jBtnPergUPD.setMinimumSize(new java.awt.Dimension(60, 60));
        jBtnPergUPD.setPreferredSize(new java.awt.Dimension(60, 60));
        jBtnPergUPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPergUPDActionPerformed(evt);
            }
        });
        jBtnPergUPD.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnPergUPD.setHorizontalTextPosition(SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/teste2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtnPergUPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBotoesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jBtnPergUPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBotoesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 375));

        jTablePerguntas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTablePerguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PERGUNTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePerguntas.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTablePerguntas);
        if (jTablePerguntas.getColumnModel().getColumnCount() > 0) {
            jTablePerguntas.getColumnModel().getColumn(0).setMinWidth(50);
            jTablePerguntas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablePerguntas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 171, 574, 195));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE PERGUNTA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 17, 574, 36));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("PERGUNTA:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 86, -1, -1));

        jTxtPergunta.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        add(jTxtPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 83, 290, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jBtnADD.setBackground(new java.awt.Color(255, 255, 255));
        jBtnADD.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jBtnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/add_btn.png"))); // NOI18N
        jBtnADD.setText("SALVAR");
        jBtnADD.setBorder(null);
        jBtnADD.setIconTextGap(10);
        jBtnADD.setMargin(new java.awt.Insets(2, 1, 2, 1));
        jBtnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnADDActionPerformed(evt);
            }
        });
        jBtnADD.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnADD.setVerticalTextPosition(SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 66, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnADDActionPerformed
        PerguntaDAO pdao = new PerguntaDAO();
        Pergunta p = new Pergunta();
        if (jTxtPergunta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencher todos os Campos!");
        } else {

            //Pega ID do item Selecionado na tabela
            int selecionado = (Integer.parseInt(jTablePerguntas.getValueAt(jTablePerguntas.getSelectedRow(), 0).toString()));

            p.setPergunta(jTxtPergunta.getText().toUpperCase());
            pdao.atualizar(p, selecionado);
            lerPerguntas();

            jTxtPergunta.setText("");

            esconderCampos();

            //Habilitar seleção de linhas novamente
            jTablePerguntas.setEnabled(true);
        }

    }//GEN-LAST:event_jBtnADDActionPerformed

    

    private void jBtnMaqUPDActionPerformed(java.awt.event.ActionEvent evt) {
        //LER OS DADOS DA LINHA SELECIOANDA
        if (jTablePerguntas.getSelectedRow() != -1) {
            //Travar a seleção de outra linha da tabela antes da alteração ser enviada
            jTablePerguntas.setEnabled(false);
            //Mostrar campos ocultos
            mostrarCampos();

            jTxtPergunta.setText(jTablePerguntas.getValueAt(jTablePerguntas.getSelectedRow(), 1).toString());

            op = 2;

        } else {
            JOptionPane.showMessageDialog(null, "Escolha uma Pergunta para alterar!");
        }
    }

    private void jBtnPergUPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPergUPDActionPerformed
        //LER OS DADOS DA LINHA SELECIOANDA
        if (jTablePerguntas.getSelectedRow() != -1) {
            //Travar a seleção de outra linha da tabela antes da alteração ser enviada
            jTablePerguntas.setEnabled(false);
            //Mostrar campos ocultos
            mostrarCampos();

            jTxtPergunta.setText(jTablePerguntas.getValueAt(jTablePerguntas.getSelectedRow(), 1).toString());

            op = 2;

        } else {
            JOptionPane.showMessageDialog(null, "Escolha uma Pergunta para alterar!");
        }
    }//GEN-LAST:event_jBtnPergUPDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnADD;
    private javax.swing.JButton jBtnPergUPD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePerguntas;
    private javax.swing.JTextField jTxtPergunta;
    // End of variables declaration//GEN-END:variables
}
