/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu;

import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Thulio
 */
public class Sobre extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
        jlblCormed.addMouseListener(this);
        jlblLoja.addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMailCormed = new javax.swing.JLabel();
        jlblCormed = new javax.swing.JLabel();
        jlblTelefone = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        CONTATO = new javax.swing.JLabel();
        SITE = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jlblLoja = new javax.swing.JLabel();
        jlblEndereco = new javax.swing.JLabel();
        jlblSisat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre o Software");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(625, 400));
        setPreferredSize(new java.awt.Dimension(625, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(625, 391));

        jlblMailCormed.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jlblMailCormed.setText("cormed@cormed.com.br");

        jlblCormed.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jlblCormed.setText("<html><body><a href=http://www.cormed.com.br>www.cormed.com.br</a>  e </body></html>");

        jlblTelefone.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jlblTelefone.setText("(31) 3482-4955");

        EMAIL.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        EMAIL.setText("E-MAIL:");

        CONTATO.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        CONTATO.setText("CONTATO:");

        SITE.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        SITE.setText("SITE:");

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_imagens/sobre.png"))); // NOI18N

        jlblLoja.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jlblLoja.setText("<html><body><a href=http://loja.cormed.com.br> loja.cormed.com.br</a></body></html>");

        jlblEndereco.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jlblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEndereco.setText("<html><body align=center> Rua Conselheiro Lafaiete, 1959 - Loja 13, Sagrada Família, Belo Horizonte, MG<br> - CEP 31035-560 -</body></html>");
        jlblEndereco.setToolTipText("");

        jlblSisat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlblSisat.setText("SISAT 2.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CONTATO)
                            .addComponent(EMAIL)
                            .addComponent(SITE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblCormed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblMailCormed)
                            .addComponent(jlblTelefone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSisat))))
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jlblSisat)
                .addGap(56, 56, 56)
                .addComponent(jlblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONTATO)
                    .addComponent(jlblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL)
                    .addComponent(jlblMailCormed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SITE)
                    .addComponent(jlblCormed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 625, 391));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTATO;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel SITE;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblCormed;
    private javax.swing.JLabel jlblEndereco;
    private javax.swing.JLabel jlblLoja;
    private javax.swing.JLabel jlblMailCormed;
    private javax.swing.JLabel jlblSisat;
    private javax.swing.JLabel jlblTelefone;
    // End of variables declaration//GEN-END:variables

    //Mouse Events para os links no Frame
    @Override
    public void mouseClicked(MouseEvent me) {

        if (me.getComponent() == jlblCormed) {
            try {
                openWebpage(new URL("http://www.cormed.com.br"));
            } catch (MalformedURLException ex) {
                Logger.getLogger(Sobre.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (me.getComponent() == jlblLoja) {
            try {
                openWebpage(new URL("http://loja.cormed.com.br"));
            } catch (MalformedURLException ex) {
                Logger.getLogger(Sobre.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent me) {
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }

    public static void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void openWebpage(URL url) {
        try {
            openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

}
